defaults: &defaults
  app_title: DingBa (DEV ENV)
  domain: "localhost:3000/r/"


development:
  <<: *defaults
  app_title: DingBa (DEV ENV)
  domain: "localhost:3000/r/"
  error: "=============Catch Error:"
  enable_invite_code: "true"

test:
  <<: *defaults
  app_title: DingBa (TEST ENV)

production:
  <<: *defaults
  app_title: DingBa
  domain: "dingba.codream.tw/r/"
  error: "=============Catch Error:"
  enable_invite_code: "true"