defaults: &defaults
  app_title: DingBa (DEV ENV)
  domain: "http://localhost:3000/r/"
  domain_clear: "http://localhost:3000/"

development:
  <<: *defaults
  app_title: DingBa (DEV ENV)
  domain: "http://localhost:3000/r/"
  domain_clear: "http://localhost:3000/"
  error: "=============Catch Error:"
  enable_invite_code: "true"

test:
  <<: *defaults
  app_title: DingBa (TEST ENV)

production:
  <<: *defaults
  app_title: DingBa
  domain: "http://dingba.codream.tw/r/"
  domain_clear: "http://dingba.codream.tw/"
  error: "=============Catch Error:"
  enable_invite_code: "true"